### PR TITLE
Add BigInt support

### PR DESCRIPTION
**Pull request by dnicolson**
This pull request fixes https://github.com/TooTallNate/plist.js/issues/96.

For additional compatibility [BigInteger.js](https://github.com/peterolson/BigInteger.js) is supported.

### CODE REVIEW

**Comment by detj** [comment]
@mreinstein Can we merge this?

**Comment by mreinstein** [comment]
The tests appear to be failing now. Please fix this, and add unit tests for the BigInt support, then I'm happy to merge.

**Comment by dnicolson** [comment]
Unit tests have been added and Node.js 10 has been added to Travis CI as `BigInt` support was added in version 10.4.0.

The build is still failing due to the broken Zuul tests though.

**Comment by mreinstein** [comment]
@TooTallNate it looks like the zuul credentials embedded in the project no longer work. can you update these please? they are causing all builds in travis to break, blocking merges. 🙏

**Pull request closed without merging**
