### PR TITLE
Fix invalid plist build when serializing a null

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by trufae** [comment]
just rebased the pr after 4 years. any chance this can be reviewed/merged before i die?

**Comment by mreinstein** [comment]
add test(s) please.

**Comment by trufae** [comment]
thanks!

**Comment by mreinstein** [comment]
something to note: this can't be published to npm until we bump the major version number. It probably makes sense to try to lump in some other API breaking changes together. I don't know if you have any interest in participating in that work, but I've outlined some thoughts on what could go into a plist.js in https://github.com/TooTallNate/plist.js/issues/113

**Pull request merged**
