### PR TITLE
exception thrown because next sometimes is null

### PR DESCRIPTION
**Pull request by waleedsamy**
exception thrown because next sometimes is null

### CODE REVIEW

**Comment by waleedsamy** [comment]
sauce secure key may be expired , so all builds fail , i used my own

**Comment by m1r4ge** [comment]
Faced the same issues with an array containing 'null' element

**Comment by TooTallNate** [comment]
Needs a regression test. Also remove the README/travis changes.

**Comment by waleedsamy** [comment]
this provide same functionality as #51 so same test it provide will pass , but instead it will check on next node lastly before accessing it's attributes so this pull request now act as double check for #51 .

**Pull request closed without merging**
