### PR TITLE
Be more strict when parsing plists

### PR DESCRIPTION
**Pull request by trufae**

### CODE REVIEW

**Comment by trufae** [comment]
related to https://github.com/TooTallNate/plist.js/issues/87

**Comment by trufae** [comment]
test case:
```
var p = require('./');

var o = p.parse(`
<plist>
<dict>
  <key>test</key>
  <string>Testing</string>
  <key>bar</key>
  <string></string>
</dict>
</plist>
`);

console.log(p.build(o));
```

**Comment by trufae** [comment]
Can i have a review on this at least? i would love to use the official module but it's broken for my usecases so i need to keep maintaining my fork

**Comment by mreinstein** [comment]
technically this is a breaking change, right? meaning this would have to be included with a major semver bump to v4, unless I misunderstand

**Comment by mreinstein** [comment]
I appreciate the PRs.  Please add at least 1 test to validate this behavior

**Comment by trufae** [comment]
Should be good to review now

**Comment by mreinstein** [comment]
Isn't an empty string still considered a valid?

**Comment by trufae** [comment]
added a test for the empty string case

**Comment by mreinstein** [comment]
maybe I misunderstood the test case. Which part of the plist is considered the invalid part? the `<strong>...` section?

**Comment by trufae** [comment]
yes. <strong> is not a valid token for a plist. so it shouldnt permit deserializing it because it results on an invalid xml that fails later on when parsing it.

i'm using this library on millions of iOS apps and i think it's fine to consider invalid what's not correct to ease catching bugs in early stages of the problem.

the output of this test without the patch results on this:

```
<plist>
<dict>
  <key>test</key>
  <key>bar</key>
  <string></string>
</dict>
</plist>
```

**Comment by mreinstein** [comment]
so basically this library switches it's philosophy from permissive to a more strict interpretation in v4, right?

I'm not opposed to this, I think it's probably better to be strict, but I want to ensure this is communicated when the v4 migration doc is written.

**Comment by trufae** [comment]
That's correct. maybe we can have an option disabled by default for this behaviour, so it doesnt breaks. will this way be merged?

also i added the missing line to run the CI on pullreqsts in here

**Pull request merged**
